version: '3.8'
services:
  mindful_postgres_db:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=mindful_dev
      - POSTGRES_USER=mindful_dev
      - POSTGRES_PASSWORD=mindful_dev
    ports:
      - 5432:5432
    volumes:
      - mindful_dev_db_data:/data/db
volumes:
  mindful_dev_db_data:
